name:        foike.org

destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['Gemfile', 'Gemfile.lock']
keep_files:  ['.git','.gitignore', '.gitkeep']
timezone:    nil

future:      true
show_drafts: nil
limit_posts: 42
highlighter: pygments

relative_permalinks: true

permalink:     none
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

host:        0.0.0.0
port:        4000
baseurl:     /
